# Generated by Django 5.1.2 on 2024-12-03 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_rename_content_comment_text_remove_poem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poem',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='poem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='poem_images/'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
